---

galaxy_info:
  author: Geert Roks
  description: >-
    Coldboot server through vendor specific BMCs using
    the Redfish API. A cold boot removes the power fully
    before turning the server back on, which resets many
    FPGAs to their default fabric/shell.
  company: ETH ZÃ¼rich - Systems Group

  license: MIT

  min_ansible_version: 2.15

  galaxy_tags: []
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

dependencies: []
