---

fpga_toolchain_releases: []

fpga_toolchain_install_path: /tools/amd
fpga_toolchain_download_path: /opt/amd/downloads

fpga_toolchain_set_bash_environment_variables: true
fpga_toolchain_uninstall_dangling_releases: false
fpga_toolchain_skip_disk_space_check: false
fpga_toolchain_enable_desktop_icons: false

fpga_toolchain_license_servers: []
fpga_toolchain_enable_jtag: false
fpga_toolchain_jtag_group: "fpga-jtag"

fpga_toolchain_amd_user_email: null
fpga_toolchain_amd_user_password: null
