---

- name: Power on Dell system
  delegate_to: localhost
  dellemc.openmanage.redfish_powerstate:
    baseuri: "{{ powerstate_bmc_url }}"
    username: "{{ powerstate_bmc_username }}"
    password: "{{ powerstate_bmc_password }}"
    reset_type: "On"
    validate_certs: false
