---

# The xrt_releases list should contain dicts with the following format
# xrt_releases:
#   - release: "YYYY.x" eg. 2024.2
#     state: present/absent
xrt_releases: []

xrt_devices: []

xrt_install_path: /opt/amd/xrt
xrt_download_path: /opt/amd/downloads

xrt_uninstall_dangling_releases: false
xrt_set_bash_environment_variables: true

# options:
#   - latest:     the latest installed xrt version (even if not defined in the xrt_releases)
#   - <release>:  The defined release
#   - absent:     Don't install
xrt_deployment_target: "latest"
xrt_development_target: "absent"
