---

vivado_packages:
  '2025.1':
    archive:
      base:
        url: https://www.xilinx.com/member/forms/download/xef.html?filename=
        package: FPGAs_AdaptiveSoCs_Unified_SDI_2025.1_0530_0145
        extention: .tar
        checksum_md5: 144b21e7a231081821d13f85495dd809
    installer:
      base:
        url: https://www.xilinx.com/member/forms/download/xef.html?filename=
        bin: FPGAs_AdaptiveSoCs_Unified_SDI_2025.1_0530_0145_Lin64.bin
        checksum_md5: d454c48fc36481c21d3255b23f9b6c73
    prerequisites:
      - libc6-dev-i386
      - net-tools
      - graphviz
      - make
      - unzip
      - zip
      - g++
      - libtinfo5
      - xvfb
      - git
      - libncurses5-dev
      - libc6-dev-i386
      - libnss3-dev
      - libgdk-pixbuf2.0-dev
      - libgtk-3-dev
      - libxss-dev
      - libasound2
      - openssl
      - fdisk
      - libsecret-1-dev

  '2024.2':
    archive:
      update2:
        url: https://www.xilinx.com/member/forms/download/xef.html?filename=
        package: FPGAs_AdaptiveSoCs_Unified_2024.2.2_0306_2141
        extention: .tar
        checksum_md5: 93abf41f18b5a0e9dedff8417b556282
      base:
        url: https://www.xilinx.com/member/forms/download/xef.html?filename=
        package: FPGAs_AdaptiveSoCs_Unified_2024.2_1113_1001
        extention: .tar
        checksum_md5: 0ca31a787bbdff82b55213522e604446
    installer:
      update2:
        url: https://www.xilinx.com/member/forms/download/xef.html?filename=
        bin: FPGAs_AdaptiveSoCs_Unified_2024.2.2_0306_2141_Lin64.bin
        checksum_md5: e7e4eb6d3eed6a192af0c0d742c718aa
      base:
        url: https://www.xilinx.com/member/forms/download/xef.html?filename=
        bin: FPGAs_AdaptiveSoCs_Unified_2024.2_1113_1001_Lin64.bin
        checksum_md5: 20c806793b3ea8d79273d5138fbd195f
    prerequisites:
      - libc6-dev-i386
      - net-tools
      - graphviz
      - make
      - unzip
      - zip
      - g++
      - libtinfo5
      - xvfb
      - git
      - libncursesw5
      - libc6-dev-i386
      - libnss3-dev
      - libgdk-pixbuf2.0-dev
      - libgtk-3-dev
      - libxss-dev
      - libasound2
      - fdisk

  '2024.1':
    archive:
      base:
        url: https://www.xilinx.com/member/forms/download/xef.html?filename=
        package: FPGAs_AdaptiveSoCs_Unified_2024.1_0522_2023
        extention: .tar.gz
        checksum_md5: 372c0b184e32001137424e395823de3c
    installer:
      base:
        url: https://www.xilinx.com/member/forms/download/xef.html?filename=
        bin: FPGAs_AdaptiveSoCs_Unified_2024.1_0522_2023_Lin64.bin
        checksum_md5: 8b0e99a41b851b50592d5d6ef1b1263d
    prerequisites:
      - libc6-dev-i386
      - net-tools
      - graphviz
      - make
      - unzip
      - zip
      - g++
      - libtinfo5
      - xvfb
      - git
      - libncursesw5
      - libc6-dev-i386


  '2023.2':
    archive:
      base:
        url: https://www.xilinx.com/member/forms/download/xef.html?filename=
        package: FPGAs_AdaptiveSoCs_Unified_2023.2_1013_2256
        extention: .tar.gz
        checksum_md5: 64d64e9b937b6fd5e98b41811c74aab2
    installer:
      base:
        url: https://www.xilinx.com/member/forms/download/xef.html?filename=
        bin: FPGAs_AdaptiveSoCs_Unified_2023.2_1013_2256_Lin64.bin
        checksum_md5: b8c785d03b754766538d6cde1277c4f0
    prerequisites:
      - libc6-dev-i386
      - net-tools
      - graphviz
      - make
      - unzip
      - g++
      - libtinfo5
      - xvfb
      - git
      - libncursesw5
      - libc6-dev-i386

  '2023.1':
    archive:
      base:
        url: https://www.xilinx.com/member/forms/download/xef.html?filename=
        package: Xilinx_Unified_2023.1_0507_1903
        extention: .tar.gz
        checksum_md5: f2011ceba52b109e3551c1d3189a8c9c
    installer:
      base:
        url: https://www.xilinx.com/member/forms/download/xef.html?filename=
        bin: Xilinx_Unified_2023.1_0507_1903_Lin64.bin
        checksum_md5: e47ad71388b27a6e2339ee82c3c8765f
    prerequisites:
      - libc6-dev-i386
      - net-tools
      - graphviz
      - make
      - unzip
      - g++
      - libtinfo5
      - xvfb
      - git
      - libncursesw5
      - libc6-dev-i386

  '2022.2':
    archive:
      base:
        url: https://www.xilinx.com/member/forms/download/xef.html?filename=
        package: Xilinx_Unified_2022.2_1014_8888
        extention: .tar.gz
        checksum_md5: 4b4e84306eb631fe67d3efb469122671
    installer:
      base:
        url: https://www.xilinx.com/member/forms/download/xef.html?filename=
        bin: Xilinx_Unified_2022.2_1014_8888_Lin64.bin
        checksum_md5: 9bf473b6be0b8531e70fd3d5c0fe4817
    prerequisites:
      - libc6-dev-i386
      - net-tools
      - graphviz
      - make
      - unzip
      - g++
      - libtinfo5
      - xvfb
      - git
      - libncursesw5
      - libc6-dev-i386
