---

- name: Update apt packages
  ansible.builtin.apt:
    update_cache: true

- name: Reload udev rules
  ansible.builtin.command: udevadm control --reload-rules
  changed_when: true
  notify: Trigger udev

- name: Trigger udev
  ansible.builtin.command: udevadm trigger
  changed_when: true

- name: Reboot system
  ansible.builtin.reboot:

- name: Reload system linker
  ansible.builtin.command:
    cmd: ldconfig
  changed_when: true
