---

#TODO: check if 300GB and 100GB are correct or too conservative for vivado_only: False and vivado_only: True respectively
- name: "Calculate the disk space that is needed for the install of all releases (100GB per release with 'tools_vivado_only: True', 300GB per release with 'vivado_only: False')"
  set_fact:
    amd_apm_tools_requested_disk_space_GB: >-
      {{
        amd_apm_releases_normalized
        | selectattr('release', 'in', releases_to_install)
        | map(attribute='tools_vivado_only')
        | map('ternary', 100, 300)
        | sum
      }}

- name: Find the mount point of the installation path
  set_fact:
    amd_apm_tools_install_mount_point: >-
      {{
        ansible_mounts
        | selectattr('mount', 'in', amd_apm_tools_install_path)
        | sort(attribute='mount', reverse=true)
        | first
      }}

- name: "Assert that there is enough disk space"
  assert:
    that: >-
      amd_apm_tools_install_mount_point.size_available | int
      is gt ( amd_apm_tools_requested_disk_space_GB | int * 1000000000)
    fail_msg: "Disk does not have the minimum space required to install the requested releases. (ca. {{ amd_apm_tools_requested_disk_space_GB }} GB needed for the installation of {{ releases_to_install | length }} new releases, only {{ amd_apm_tools_install_mount_point.size_available | int }} GB available on disk). Consider making space on the drive or adding 'vivado_only: True' to some releases. An install with 'vivado_only: True' takes approximately 100GB per release, otherwise it takes approxmately 300 GB."
