---

rocm_supported_versions:
  - '7.1.1'
  - '7.1.0'
  - '7.0.2'
  - '7.0.1'
  - '7.0.0'
  - '6.4.4'
  - '6.4.3'
  - '6.4.2'
  - '6.4.1'
  - '6.4.0'
  - '6.3.4'
  - '6.3.3'
  - '6.3.2'
  - '6.3.1'
  - '6.3.0'
  - '6.2.4'
  - '6.2.3'
  - '6.2.2'
  - '6.2.1'
  - '6.2.0'
  - '6.1.5'
  - '6.1.4'
  - '6.1.3'
  - '6.1.2'
  - '6.1.1'
  - '6.1.0'
  - '6.0.3'
  - '6.0.2'
  - '6.0.1'
  - '6.0.0'
  - '5.7.3'
  - '5.7.2'
  - '5.7.1'
  - '5.7.0'
  - '5.6.1'
  - '5.6.0'
  - '5.5.3'
  - '5.5.2'
  - '5.5.1'
  - '5.5.0'
  - '5.4.6'
  - '5.4.5'
  - '5.4.3'
  - '5.4.2'
  - '5.4.1'
  - '5.4.0'
  - '5.3.3'
  - '5.3.2'
  - '5.3.0'
  - '5.2.5'
  - '5.2.4'
  - '5.2.3'
  - '5.2.1'
  - '5.2.0'
  - '5.1.4'
  - '5.1.3'
  - '5.1.2'
  - '5.1.1'
  - '5.1.0'

rocm_supported_amdgpu_kernel_versions:
  - '30.20.0'
  - '30.10.3'
  - '30.10.2'
  - '30.10.1'
  - '30.10.0'
  - '6.4.4'
  - '6.4.3'
  - '6.4.2.1'
  - '6.4.2'
  - '6.4.1'
  - '6.4.0'
  - '6.3.4'
  - '6.3.3'
  - '6.3.2'
  - '6.3.1'
  - '6.3.0'
  - '6.2.4'
  - '6.2.3'
  - '6.2.2'
  - '6.2.1'
  - '6.2.0'
  - '6.1.4'
  - '6.1.3'
  - '6.1.2'
  - '6.1.1'
  - '6.1.0'
  - '6.0.3'
  - '6.0.2'
  - '6.0.1'
  - '6.0.0'
  - '5.7.3'
  - '5.7.2'
  - '5.7.1'
  - '5.7.0'
  - '5.6.1'
  - '5.6.0'
  - '5.5.3'
  - '5.5.2'
  - '5.5.1'
  - '5.5.0'
  - '5.4.6'
  - '5.4.5'
  - '5.4.3'
  - '5.4.2'
  - '5.4.1'
  - '5.4.0'
  - '5.3.3'
  - '5.3.2'
  - '5.3.0'

# Compatibility matrix between AMD GPU driver (key) and Supported ROCm versions (value)
# https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/user-kernel-space-compat-matrix.html
rocm_compatibility:
  '30.20':
    - '6.3'
    - '6.4'
    - '7.0'
    - '7.1'
  '30.10':
    - '6.2'
    - '6.3'
    - '6.4'
    - '7.0'
    - '7.1'
  '6.4':
    - '6.1'
    - '6.2'
    - '6.3'
    - '6.4'
    - '7.0'
    - '7.1'
  '6.3':
    - '6.1'
    - '6.2'
    - '6.3'
    - '6.4'
    - '7.0'
  '6.2':
    - '6.0'
    - '6.1'
    - '6.2'
    - '6.3'
    - '6.4'
    - '7.0'
  '6.1':
    - '5.7'
    - '6.0'
    - '6.1'
    - '6.2'
    - '6.3'
    - '6.4'
  '6.0':
    - '5.6'
    - '5.7'
    - '6.0'
    - '6.1'
    - '6.2'
  '5.7':
    - '5.5'
    - '5.6'
    - '5.7'
    - '6.0'
    - '6.1'
  '5.6':
    - '5.4'
    - '5.5'
    - '5.6'
    - '5.7'
    - '6.0'
  '5.5':
    - '5.3'
    - '5.4'
    - '5.5'
    - '5.6'
    - '5.7'
  '5.4':
    - '5.2'
    - '5.3'
    - '5.4'
    - '5.5'
    - '5.6'
  '5.3':
    - '5.1'
    - '5.2'
    - '5.3'
    - '5.4'
    - '5.5'
