---

##
# Parameters:
#   - `vivado_release`:        Object containing install info: release, vivado_only, update_level (required)

# FACTS GATHERING
#
- name: "[{{ vivado_release.release }}] Load release options"
  ansible.builtin.set_fact:
    release: "{{ vivado_release.release }}"
    vivado_only: "{{ vivado_release.vivado_only }}"
    update_level: "{{ vivado_release.update_level }}"

- name: "[{{ release }}] Set AMD Toolchain facts"
  ansible.builtin.set_fact:
    vivado_installer_bin: >-
      {{ vivado_packages[release]['installer'][update_level]['bin'] }}
    vivado_installer_checksum: >-
      {{ vivado_packages[release]['installer'][update_level]['checksum_md5'] }}
    vivado_prerequisites: >-
      {{ vivado_packages[release]['prerequisites'] }}

- name: "[{{ release }}] Set Tools installer path fact"
  ansible.builtin.set_fact:
    vivado_installer: >-
      {{ vivado_download_path }}/{{ release }}/{{ vivado_installer_bin }}

- name: "[{{ release }}] Assert that email and password are set for AMD installer tool"
  ansible.builtin.assert:
    that:
      - vivado_amd_user_email is not none
      - vivado_amd_user_email is string
      - vivado_amd_user_email is match("^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$")
      - vivado_amd_user_password is not none
      - vivado_amd_user_password is string
    fail_msg: >-
      Either or both `vivado_amd_user_email` and `vivado_amd_user_password` have
      not been set.
      'vivado_amd_user_email' must be a valid email address (e.g., user@example.com).


# PREPARE INSTALLER

- name: "[{{ release }}] Gather stats about Tools installer"
  ansible.builtin.stat:
    path: "{{ vivado_installer }}"
    checksum_algorithm: md5
    get_checksum: true
  register: vivado_installer_stats

- name: "[{{ release }}] Assert that the installer is available"
  ansible.builtin.assert:
    that:
      - vivado_installer_stats.stat.exists
    fail_msg: >-
      [ERROR] Can't find the AMD tools installer: {{ vivado_installer }}.
      Please download it from
      https://www.xilinx.com/support/download/index.html/content/xilinx/en/downloadNav/vitis.html

- name: "[{{ release }}] Assert that the checksum of the installer is correct"
  ansible.builtin.assert:
    that:
      - vivado_installer_stats.stat.checksum == vivado_installer_checksum
    fail_msg: >-
      [ERROR] Checksum of the installer is incorrect: {{ vivado_installer }}.
      The file might have been tampered with. Please download the correct version from
      https://www.xilinx.com/support/download/index.html/content/xilinx/en/downloadNav/vitis.html

- name: "[{{ release }}] Set permissions of installer to allow execution"
  ansible.builtin.file:
    path: "{{ vivado_installer }}"
    mode: 755


# AMD AUTHENTICATION

- name: "[{{ release }}] Check AMD authentication key file stats"
  ansible.builtin.stat:
    path: "/root/.Xilinx/wi_authentication_key"
  register: vivado_installer_auth_file_stats

- name: "[{{ release }}] Set auth_valid default to whether the auth file exists"
  ansible.builtin.set_fact:
    vivado_installer_auth_valid: >-
      {{
        vivado_installer_auth_file_stats.stat.exists
        and
        vivado_installer_auth_file_stats.stat.mode == '0400'
      }}

- name: "[{{ release }}] Read and validate authentication data"
  when: vivado_installer_auth_valid
  block:
    - name: "[{{ release }}] Get authentication file contents"
      ansible.builtin.slurp:
        src: /root/.Xilinx/wi_authentication_key
      register: vivado_installer_auth_data

    - name: "[{{ release }}] Parse authentication file and check whether it is valid"
      ansible.builtin.set_fact:
        vivado_installer_auth_valid: >-
          {{
            (
              vivado_installer_auth_data['content']
              | b64decode | from_json
            )['username'] == vivado_amd_user_email
            and
            (
              (
                (
                  (
                    vivado_installer_auth_data['content'] | b64decode | from_json
                  )['expiration']
                  | replace('\\/', '/') | to_datetime('%m/%d/%Y %I:%M %p')
                ) -
                (ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ'))
              ).total_seconds() > 3600
            )
          }}
  rescue:
    - name: "[{{ release }}] Handle AMD authentication file parsing errors"
      ansible.builtin.set_fact:
        vivado_installer_auth_valid: false

- name: "[{{ release }}] Generate AMD Auth token"
  ansible.builtin.expect:
    command: "{{ vivado_installer }} --nox11 -- --batch AuthTokenGen"
    responses:
      "E-mail Address:":
        - "{{ vivado_amd_user_email }}"
      "Password:":
        - "{{ vivado_amd_user_password }}"
  when: not vivado_installer_auth_valid


# INSTALL

- name: "[{{ release }}] Install prerequisite packages"
  ansible.builtin.package:
    name: "{{ vivado_prerequisites }}"
    state: present

- name: "[{{ release }}] Ensure Vitis install directory exists"
  ansible.builtin.file:
    path: "{{ vivado_install_path }}"
    state: directory

- name: "[{{ release }}] Ensure config directory exists for the {{ release }} release"
  ansible.builtin.file:
    path: "/root/.Xilinx/{{ release }}"
    state: directory

- name: "[{{ release }}] Generate AMD tools configuration file"
  ansible.builtin.expect:
    command: >-
      {{ vivado_installer }} --nox11 --
      --batch ConfigGen
      --location {{ vivado_install_path }}
      --product '{% if vivado_only %}Vivado{% else %}Vitis{% endif %}'
    responses:
      "Please choose: ":
        - "1"

- name: "[{{ release }}] Copy install_config to release directory"
  ansible.builtin.copy:
    src: /root/.Xilinx/install_config.txt
    dest: "/root/.Xilinx/{{ release }}/install_config.txt"
    remote_src: true

- name: "[{{ release }}] Edit install config"
  ansible.builtin.include_tasks: edit-install-config.yml
  vars:
    config_path: "/root/.Xilinx/{{ release }}/install_config.txt"

- name: "[{{ release }}] Install Tools (usually takes about 2 hours, but can take up to 6 hours...)"
  ansible.builtin.command: >-
    {{ vivado_installer }} --nox11 --
    --batch Install
    --config /root/.Xilinx/{{ release }}/install_config.txt
    --agree XilinxEULA,3rdPartyEULA"
  vars:
    # wait up to 6 hours
    ansible_command_timout: 21600
    ansible_ssh_timout: 21600
