---

- name: Reload udev rules
  ansible.builtin.command: udevadm control --reload-rules
  changed_when: true
  notify: Trigger udev

- name: Trigger udev
  ansible.builtin.command: udevadm trigger
  changed_when: true
